workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: release_Iryna
          include: true
    environment:
      groups:
        - firebase_credentials
    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        ios:
          app_id: "1:312340303940:ios:21ef4c839afc3c369fac11"
          groups:
            - tester-groups
      email:
        recipients:
          - o.frankiv@ukma.edu.ua
          - iryna.nazar@ukma.edu.ua
