workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: release_Iryna
          include: true
    environment:
      groups:
        - firebase_credentials
    scripts:
      - name: Install fastlane
        script: |
          gem install bundler
          bundle install
      - name: Build and export
        script: bundle exec fastlane build_and_export
        ignore_failure: true
      - name: Build for iOS
        script: flutter build ios
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData//Build//*.dSYM
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
      ios:
        app_id: "1:312340303940:ios:21ef4c839afc3c369fac11"
        groups:
          - tester-groups
        email:
          recipients:
            - o.frankiv@ukma.edu.ua
            - iryna.nazar@ukma.edu.ua
