workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'release_Iryna'
          include: true
    environment:
      groups:
        - firebase_credentials
          vars:
            BUNDLE_ID: "ira.nazar.CatsAndModules-IrynaNazar"
            XCODE_WORKSPACE: "CatsAndModules_IrynaNazar.xcodeproj"
            XCODE_SCHEME: "CatsAndModules_IrynaNazar"
    scripts:
      - name: Build ipa
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
        ios:
          app_id: "1:312340303940:ios:21ef4c839afc3c369fac11"
          groups:
            - tester-groups
      email:
        recipients:
          - o.frankiv@ukma.edu.ua
          - iryna.nazar@ukma.edu.ua
