workflows:
    sample-workflow:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: release_Iryna
                   include: true
                   source: true

