# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :build_and_export do
    increment_build_number(
      xcodeproj: 'CatsAndModules_IrynaNazar.xcodeproj',
      build_number: "1.1"
    )
    gym

#     build_app(
#   scheme: "CatsAndModules_IrynaNazar",
#   export_method: "development",
#   export_options: {
#     provisioningProfiles: {
#       "ira.nazar.CatsAndModules-IrynaNazar" => "2fea7968-7e02-4e17-babd-a9133c9704ff"
#     }
#   }
# )
    # add actions here: https://docs.fastlane.tools/actions
    # firebase_app_distribution(service_credentials_file: "../fir-catappnazar-919ef08bfe8a.json",
    # ipa_path: "CatsAndModules_IrynaNazar.ipa",
    # release_notes: "Release notes",
    # testers: "o.frankiv@ukma.edu.ua")
  end



  lane :take_screenshots do
    snapshot
  end
end
